### ISSUE TITLE
How to use external service in  Kubernetes Ingress resource ?

### ISSUE THREAD

**Issue by szhengli** [apache/apisix-ingress-controller#1993] opened 2023-09-30 14:24 UTC
### Issue description

after reading the doc about "Using External Services In ApisixUpstream", so how to  How to use external service in  Kubernetes Ingress resource ?

### Environment

apache/apisix-ingress-controller:1.6.1

**Comment by tao12345666333** [comment] 2023-09-30 23:17
This is a duplicate of #1991

I will close this one.

It's not support

**Closed** 2023-09-30 23:17 UTC
Labels: triage/duplicate
