### ISSUE TITLE
Failed to watch *v1.Ingress &Failed to watch *v2alpha1.ApisixClusterConfig

### ISSUE THREAD

**Issue by kingGang** [apache/apisix-ingress-controller#538] opened 2021-06-08 07:23 UTC
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
 0.6.0
* your Kubernetes cluster version (output of `kubectl version`);
azure k8s v1.18.14
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).
unkown

apisix-ingress-controller 运行之后 出现两条报警日志，apisix各项功能正常，但是我不知道他会不会有其他影响，日志如下：
[GIN] 2021/06/08 - 15:16:21 | 200 |      35.302µs |      10.0.192.4 | GET      "/healthz"
E0608 15:16:21.192060       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: the server could not find the requested resource
2021-06-08T15:16:21+08:00       warn    ingress/endpoint.go:93  service kube-system/kube-controller-manager was deleted
E0608 15:16:21.552209       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v2alpha1.ApisixClusterConfig: failed to list *v2alpha1.ApisixClusterConfig: apisixclusterconfigs.apisix.apache.org is forbidden: User "system:serviceaccount:ingress-apisix:apisix-apisix-ingress-controller" cannot list resource "apisixclusterconfigs" in API group "apisix.apache.org" at the cluster scope
[GIN] 2021/06/08 - 15:16:22 | 200 |      34.001µs |      10.0.192.4 | GET      "/healthz"
2021-06-08T15:16:22+08:00       warn    ingress/endpoint.go:93  service kube-system/kube-scheduler was deleted
2021-06-08T15:16:23+08:00       warn    ingress/endpoint.go:93  service kube-system/kube-controller-manager was deleted
2021-06-08T15:16:24+08:00       warn    ingress/endpoint.go:93  service kube-system/kube-scheduler was deleted
2021-06-08T15:16:25+08:00       warn    ingress/endpoint.go:93  service kube-system/kube-controller-manager was deleted

**Comment by tokers** [comment] 2021-06-09 01:28
@kingGang 
How did you install Apache APISIX Ingress Controller? You should apply the newest CRD files, see https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1beta1.

**Comment by kingGang** [comment] 2021-06-09 06:28
> @kingGang
> How did you install Apache APISIX Ingress Controller? You should apply the newest CRD files, see https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1beta1.

我是通过helm 安装（helm.sh/chart: apisix-0.3.1），后面把ingress-controller 由0.5.0，改成了0.6.0；
按照你的说法我重新apply CRD文件，且重新启动了 ingress-controller pod，一样的问题还是存在

**Comment by kingGang** [comment] 2021-06-09 06:31
> @kingGang
> How did you install Apache APISIX Ingress Controller? You should apply the newest CRD files, see https://github.com/apache/apisix-ingress-controller/blob/master/samples/deploy/crd/v1beta1.

我是通过helm 安装（helm.sh/chart: apisix-0.3.1），后面把ingress-controller 由0.5.0，改成了0.6.0；
按照你的说法我重新apply CRD文件，且重新启动了 ingress-controller pod，一样的问题还是存在

**Comment by tokers** [comment] 2021-06-09 11:34
@kingGang Oops, I took some wrong words, the problem was caused by the incorrect service account settings.

@tao12345666333 @lingsamuel We may need to publish a new helm repo.

**Comment by tao12345666333** [comment] 2021-06-09 11:47
yep, my PR hasn't been merged

**Comment by kingGang** [comment] 2021-06-10 06:52
现在是需要等你们那边更新 helm repo才能解决吗？我还能做些什么吗？

**Comment by tokers** [comment] 2021-06-10 09:52
> 现在是需要等你们那边更新 helm repo才能解决吗？我还能做些什么吗？

We'll release it as soon as possible, PR is ongoing.

**Comment by tao12345666333** [comment] 2021-06-19 03:27
@kingGang 

you can try to clone this repo https://github.com/apache/apisix-helm-chart and run helm install. thanks.

**Comment by tao12345666333** [comment] 2021-06-29 12:25
@kingGang Is the problem solved?

**Comment by tao12345666333** [comment] 2022-03-04 16:08
This issue has not been updated for too long, I will close it. If you continue to experience this problem, please feel free to reopen it.

**Closed by tao12345666333** 2022-03-04 16:08 UTC
Labels: wait for update
