### ISSUE TITLE
bug: `timeout` cannot sync successfully

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix-ingress-controller#1737] opened 2023-03-21 07:53 UTC
### Current Behavior

Create a ApisixRoute with timeout, we can not find any `timeout` config in route via apisix-dashboard

### Expected Behavior

`timeout config` sync successfully

### Error Logs

no error log

### Steps to Reproduce

1. install Apisix ingress controller via helm chart with version 1.6.0
2. create a ApisixRoute with `timeout`:
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-upstream
spec:
  externalNodes:
    - type: Domain
      name: 127.0.0.1
      port: 8088
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
spec:
  http:
    - name: rule1
      timeout:
        connect: 60s
        read: 60s
        send: 60s
      match:
        hosts:
          - local.httpbin.org
        paths:
          - /*
      upstreams:
        - name: httpbin-upstream
```
3. check this ApisixRoute with kubectl command: `kubectl get ar httpbin-route -o yaml`, output:
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apisix.apache.org/v2","kind":"ApisixRoute","metadata":{"annotations":{},"name":"httpbin-route","namespace":"default"},"spec":{"http":[{"match":{"hosts":["local.httpbin.org"],"paths":["/*"]},"name":"rule1","timeout":{"connect":"60s","read":"60s","send":"60s"},"upstreams":[{"name":"httpbin-upstream"}]}]}}
  creationTimestamp: "2023-03-21T07:35:14Z"
  generation: 1
  name: httpbin-route
  namespace: default
  resourceVersion: "210787"
  uid: d51925fb-a30b-4af6-9aae-6cdc5e3b7e88
spec:
  http:
  - match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    name: rule1
    timeout:
      connect: 60s
      read: 60s
      send: 60s
    upstreams:
    - name: httpbin-upstream
status:
  conditions:
  - message: Sync Successfully
    observedGeneration: 1
    reason: ResourcesSynced
    status: "True"
    type: ResourcesAvailable
```
4. check this route via apisix-dashboard:
- upstream data: 
```yaml
{
  "nodes": [
    {
      "host": "127.0.0.1",
      "port": 8088,
      "weight": 100
    }
  ],
  "type": "roundrobin",
  "hash_on": "vars",
  "scheme": "http",
  "pass_host": "pass",
  "name": "default_httpbin-upstream",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "labels": {
    "managed-by": "apisix-ingress-controller",
    "meta_weight": "100"
  }
}
```
- route data:
```yaml
{
  "uris": [
    "/*"
  ],
  "name": "default_httpbin-route_rule1",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "hosts": [
    "local.httpbin.org"
  ],
  "upstream_id": "f69035a2",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  },
  "status": 1
}
```

### Environment

- APISIX Ingress controller version (run `apisix-ingress-controller version --long`)
```sh
Version: 1.6.0
Git SHA: no-git-module
Go Version: go1.19.4
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```
- Kubernetes cluster version (run `kubectl version`)
```sh
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

```
- OS version if running APISIX Ingress controller in a bare-metal environment (run `uname -a`)
```sh
Darwin fabricedeMacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
```

**Comment by AlinsRan** [comment] 2023-03-22 00:56
Let me check it.

**Comment by AlinsRan** [comment] 2023-03-22 01:05
It seems that I cannot reproduce it. Is there any related error log.
```json
{
    "list": [
        {
            "value": {
                "labels": {
                    "managed-by": "apisix-ingress-controller"
                },
                "uris": [
                    "\/*"
                ],
                "create_time": 1679446852,
                "priority": 0,
                "update_time": 1679446852,
                "upstream_id": "f69035a2",
                "hosts": [
                    "local.httpbin.org"
                ],
                "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
                "timeout": {
                    "send": 60,
                    "read": 60,
                    "connect": 60
                },
                "name": "default_httpbin-route_rule1",
                "id": "46eb0e41",
                "status": 1
            },
            "modifiedIndex": 18,
            "key": "\/apisix\/routes\/46eb0e41",
            "createdIndex": 16
        }
    ],
    "total": 1
}
```

**Comment by Fabriceli** [comment] 2023-03-22 01:11
@AlinsRan APISIX version:
```sh
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version
3.1.0
```

**Comment by AlinsRan** [comment] 2023-03-22 01:15
APISIX Version: apisix:3.1.0-debian
![image](https://user-images.githubusercontent.com/79972061/226776633-4af319d7-ddfe-4602-9f70-83c69e1412c2.png)

**Comment by Fabriceli** [comment] 2023-03-22 01:27
@AlinsRan check from admin API:
```json
{
	"value": {
		"id": "46eb0e41",
		"name": "default_httpbin-route_rule1",
		"hosts": ["local.httpbin.org"],
		"labels": {
			"managed-by": "apisix-ingress-controller"
		},
		"priority": 0,
		"desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
		"create_time": 1679384114,
		"uris": ["\/*"],
		"update_time": 1679448144,
		"timeout": {
			"connect": 60,
			"read": 60,
			"send": 60
		},
		"upstream_id": "f69035a2",
		"status": 1
	},
	"modifiedIndex": 2228,
	"createdIndex": 1565,
	"key": "\/apisix\/routes\/46eb0e41"
}
```

**Comment by Fabriceli** [comment] 2023-03-22 01:28
It means there is a bug in apisix-dashboard to show the route info with `timeout` config

**Comment by AlinsRan** [comment] 2023-03-22 02:15
Yeah, I think so too.

**Comment by tao12345666333** [comment] 2023-03-22 08:14
It looks like you have submitted https://github.com/apache/apisix-dashboard/issues/2779

I will close this issue, thanks for your report

**Closed by tao12345666333** 2023-03-22 08:14 UTC
