### ISSUE TITLE
bug: The newly created namespace will not be watched

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix-ingress-controller#741] opened 2021-11-08 03:42 UTC
### Environment

* controller: master 65f7c88193eb6e83b2bb4ca87a981321a99503e5

### Minimal test code / Steps to reproduce the issue
1. start controller
2. create a new namespace
3. namespace will not store to `watchingNamespace`

### The reason of the bug
![image](https://user-images.githubusercontent.com/10919124/140680435-710bf50e-b7af-4027-a871-e44fac82a12b.png)
The method `IsSubsetOf` return `false` when `watchingLabels` is empty

![image](https://user-images.githubusercontent.com/10919124/140680620-65c6386e-23d6-4045-9801-0dfd67edb17e.png)

I think should return `true` when the `s` is empty

**Comment by tao12345666333** [comment] 2021-11-08 03:57
ping @gxthrj  PTAL

**Comment by gxthrj** [comment] 2021-11-08 04:46
The reason for the issue is the way to determine if `sync.Map` is empty has wrong. It can not be nil anyway.

**Comment by gxthrj** [comment] 2021-11-08 08:28
> The method IsSubsetOf return false when watchingLabels is empty
I think should return true when the s is empty

Yes, you are right. Thanks for the report.

**Comment by tao12345666333** [comment] 2021-11-26 03:28
#742 has been merged, I will close this one. Feel free to reopen it if you have any questions.

**Closed by tao12345666333** 2021-11-26 03:28 UTC
Labels: bug, triage/accepted
