### ISSUE TITLE
bug: When k8s service is deleted, the APISIX Upstream nodes field is not cleared

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix-ingress-controller#674] opened 2021-09-10 06:21 UTC
### Issue description
When k8s service is deleted, the APISIX Upstream nodes field is not cleared
### Environment

* your apisix-ingress-controller version: v1.2
* your Kubernetes cluster version: v1.16

### Minimal test code / Steps to reproduce the issue

1. delete k8s service.
2. query APISIX upstream  nodes field

### What's the actual result? (including assertion message & call stack if applicable)
remaining history of upstream node
### What's the expected result?
upstream nodes cleared

**Comment by tokers** [comment] 2021-09-11 14:57
This is a known behavior, see https://github.com/apache/apisix-ingress-controller/blob/1e1be7401ba3707ba660a7d61df5118fc5725eff/pkg/ingress/controller.go#L529.

From the proxy point of view, the result is similar, requests will be failed no matter whether we clean the nodes.

Of course, we do need make some reactions for the Services/Endpoints delete events, PR's welcome to optimize it.

**Comment by Donghui0** [comment] 2021-09-13 11:59
> This is a known behavior, see
> 
> https://github.com/apache/apisix-ingress-controller/blob/1e1be7401ba3707ba660a7d61df5118fc5725eff/pkg/ingress/controller.go#L529
> 
> .
> From the proxy point of view, the result is similar, requests will be failed no matter whether we clean the nodes.
> 
> Of course, we do need to make some reactions for the Services/Endpoints delete events, PR's welcome to optimize it.

There will be problems in special scenarios: the node ip is allocated by other containers.

**Comment by tokers** [comment] 2021-09-13 13:21
> > This is a known behavior, see
> > https://github.com/apache/apisix-ingress-controller/blob/1e1be7401ba3707ba660a7d61df5118fc5725eff/pkg/ingress/controller.go#L529
> > 
> > .
> > From the proxy point of view, the result is similar, requests will be failed no matter whether we clean the nodes.
> > Of course, we do need to make some reactions for the Services/Endpoints delete events, PR's welcome to optimize it.
> 
> There will be problems in special scenarios: the node ip is allocated by other containers.

Fair enough, PR's welcome to fix this.

**Comment by tao12345666333** [comment] 2021-09-14 23:38
Thanks for your feedback, it is not difficult to fix it, welcome to submit a PR

**Comment by gxthrj** [comment] 2021-09-15 05:47
I hope this can have an overall solution and then coding.

Upstream management in the ingress controller has become more complicated, it will be affected in many ways，for example, the resources of  k8s svc , ApisixUpstream and ApisixRoute ，There are subset-related configurations in ApisixRoute and ApisixUpstream.

**Comment by tokers** [comment] 2021-09-16 01:05
> I hope this can have an overall solution and then coding.
> 
> Upstream management in the ingress controller has become more complicated, it will be affected in many ways，for example, the resources of k8s svc , ApisixUpstream and ApisixRoute ，There are subset-related configurations in ApisixRoute and ApisixUpstream.

It doesn't affect ApisixRoute, but it will affect multiple Upstream objects in APISIX due to subset mechanics.

**Comment by AlinsRan** [comment] 2022-05-26 02:32
I'm trying to solve this problem, I have two implementation schemes, which need to be confirmed:

1. Add `cache` (go-memdb) to `controller` and maintain a ` upstream_ services {servicename -- > []upstream_id}`. The `upstreamController` is responsible for write, When [] is 0, this record is killed. The `endpoint` is responsible for reading and updating the node field of apifix when the services are updated.
2. This status info is maintained by `endpoint` or `upstreamController`. Mutual communication and high coupling are required.

I prefer the first, any better proposal?

**Comment by tao12345666333** [comment] 2022-05-26 06:23
@AlinsRan thanks.

Currently we use the following methods to generate the upstream name. 
https://github.com/apache/apisix-ingress-controller/blob/49dd015085a68ce4c26ba60076ef281ed71af2aa/pkg/types/apisix/v1/types.go#L425-L450

Then generate its ID.
https://github.com/apache/apisix-ingress-controller/blob/49dd015085a68ce4c26ba60076ef281ed71af2aa/pkg/id/idgen.go#L25-L39

Maintaining the mapping relationship between Service and Upstream, I think it is a better choice.

**Comment by AlinsRan** [comment] 2022-05-26 06:32
> @AlinsRan thanks.
> 
> Currently we use the following methods to generate the upstream name.
> 
> https://github.com/apache/apisix-ingress-controller/blob/49dd015085a68ce4c26ba60076ef281ed71af2aa/pkg/types/apisix/v1/types.go#L425-L450
> 
> Then generate its ID.
> 
> https://github.com/apache/apisix-ingress-controller/blob/49dd015085a68ce4c26ba60076ef281ed71af2aa/pkg/id/idgen.go#L25-L39
> 
> Maintaining the mapping relationship between Service and Upstream, I think it is a better choice.
> 
> Here we need to clear the node field of Upstream in APISIX after discovering that the service has been deleted

I understand, After the SVC is deleted, it should also be written to `apisix` when it is created.

The question is how to maintain this relationship.

**Comment by tao12345666333** [comment] 2022-06-30 09:23
#1064  has been merged. I will close this one. thanks

**Closed by tao12345666333** 2022-06-30 09:23 UTC
Labels: help wanted, triage/accepted
