### ISSUE TITLE
bug: etcd routes will not update when i delete pod  apisix-ingress-controller and recreate

### ISSUE THREAD

**Issue by shuoshadow** [apache/apisix-ingress-controller#444] opened 2021-05-12 11:18 UTC
### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1. apply apisixroute resource
2. delete pod  apisix-ingress-controller
3. edit  apisixroute resource
4. etcd routes will not update
![image](https://user-images.githubusercontent.com/10016360/117966569-a1eaa180-b356-11eb-9158-0966c0a928c4.png)
![image](https://user-images.githubusercontent.com/10016360/117966630-b4fd7180-b356-11eb-9bde-3fbdb58dd419.png)

**Comment by tokers** [comment] 2021-05-12 11:20
@shuoshadow In which step you re-deploy apisix-ingress-controller? It's not recorded in your reproduce steps.

**Comment by shuoshadow** [comment] 2021-05-12 12:13
> @shuoshadow In which step you re-deploy apisix-ingress-controller? It's not recorded in your reproduce steps.

after i deploy apisixroute resource,  than i delete pod and recreate

when apisix-ingress-controller pod recreated, i changed apisixroute config and apply it, but it was not update to etcd

**Comment by gxthrj** [comment] 2021-05-12 13:29
@shuoshadow Please show the log of apisix-ingress-controller, if the configuration in etcd are not update, There must be some error logs about that.

**Comment by tokers** [comment] 2021-05-13 02:04
@shuoshadow Note since apisix-ingress-controller uses a leader-election mechanism, when you destroyed the apisix-ingress-controller, the lease resource was still there, after you recreated a new instance, it might run as the candidate for a while, so you may need to wait some times.

**Comment by tao12345666333** [comment] 2022-03-23 04:49
I have not reproduced locally.

And this issue has not been updated for too long, I will close it. If your issue is not resolved, feel free to reopen it, or create a new issue. Thanks!

**Closed by tao12345666333** 2022-03-23 04:49 UTC
Labels: wait for update
