### ISSUE TITLE
request help: failed to wait the default cluster to be ready:

### ISSUE THREAD

**Issue by pioneer-hash** [apache/apisix-ingress-controller#427] opened 2021-05-08 04:18 UTC
### Issue description
A few days ago, when the deployment was completed, there was no problem in synchronizing the data. Now, there was an error when synchronizing the configuration. Could you please help me to see what caused the error
```
E0508 11:58:49.908189       1 leaderelection.go:325] error retrieving resource lock gray-publish/ingress-apisix-leader: Get https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/gray-publish/leases/ingress-apisix-leader: context deadline exceeded
2021-05-08T11:58:49+08:00       info    controller/controller.go:202    LeaderElection  {"message": "sitech-gray-ingress-controller-7779b6bd88-chpnm stopped leading", "event_type": "Normal"}
I0508 11:58:49.908333       1 leaderelection.go:278] failed to renew lease gray-publish/ingress-apisix-leader: timed out waiting for the condition
E0508 11:58:49.908405       1 leaderelection.go:301] Failed to release lock: resource name may not be empty
2021-05-08T11:58:49+08:00       info    controller/controller.go:249    controller now is running as a candidate        {"namespace": "gray-publish", "pod": "sitech-gray-ingress-controller-7779b6bd88-chpnm"}
I0508 11:58:49.908450       1 leaderelection.go:243] attempting to acquire leader lease gray-publish/ingress-apisix-leader...
[GIN] 2021/05/08 - 11:58:50 | 200 |      64.605µs |     172.21.9.40 | GET      "/healthz"
2021-05-08T11:58:52+08:00       info    controller/controller.go:202    LeaderElection  {"message": "sitech-gray-ingress-controller-7779b6bd88-chpnm became leader", "event_type": "Normal"}
I0508 11:58:52.561077       1 leaderelection.go:253] successfully acquired lease gray-publish/ingress-apisix-leader
2021-05-08T11:58:52+08:00       info    controller/controller.go:277    controller now is running as leader     {"namespace": "gray-publish", "pod": "sitech-gray-ingress-controller-7779b6bd88-chpnm"}
2021-05-08T11:58:52+08:00       error   controller/controller.go:296    failed to wait the default cluster to be ready: Get http://sitech-gray-admin:9180/apisix/admin/routes: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```
I I go inside pod of apisix-ingress-controller and get Route information directly it was successful
```
/ingress-apisix # wget http://apisix-admin:9180/apisix/admin/routes  --header="X-API-Key: edd1c9f034335f136f87ad84b625c8f1"
wget: bad address 'apisix-admin:9180'
/ingress-apisix # wget http://sitech-gray-admin:9180/apisix/admin/routes  --header="X-API-Key: edd1c9f034335f136f87ad84b625c8f1"
Connecting to sitech-gray-admin:9180 (10.111.0.24:9180)
saving to 'routes'
routes               100% |******************************************************************************************************|   908  0:00:00 ETA
'routes' saved
/ingress-apisix # ls
apisix-ingress-controller  conf                       routes
```
### Environment
* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`); 
 apisix-ingress-controller version :0.5.0
 apisx-version:2.5
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

**Comment by tokers** [comment] 2021-05-08 05:18
This line:

```
E0508 11:58:49.908189       1 leaderelection.go:325] error retrieving resource lock gray-publish/ingress-apisix-leader: Get https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/gray-publish/leases/ingress-apisix-leader: context deadline exceeded
```

is the root cause, it seems your kube-apiserver is not running normally.

**Comment by pioneer-hash** [comment] 2021-05-08 06:05
> This line:
> 
> ```
> E0508 11:58:49.908189       1 leaderelection.go:325] error retrieving resource lock gray-publish/ingress-apisix-leader: Get https://10.96.0.1:443/apis/coordination.k8s.io/v1/namespaces/gray-publish/leases/ingress-apisix-leader: context deadline exceeded
> ```
> 
> is the root cause, it seems your kube-apiserver is not running normally.

Could you please tell me what command I can use to query the status of kube-apiserver

**Comment by tokers** [comment] 2021-05-08 06:41
> 2021-05-08T11:58:52+08:00       error   controller/controller.go:296    failed to wait the default cluster to be ready: Get http://sitech-gray-admin:9180/apisix/admin/routes: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

How did you configure apisix-ingress-controller? Especially the baseURL.

**Comment by pioneer-hash** [comment] 2021-05-08 06:45
> How did you configure apisix-ingress-controller? Especially the baseURL.

apisix install
```
helm install sitech-gray . -n gray-publish \
  --set image.repository="172.21.9.35:30002/gray-stare/gray" \
  --set image.tag="2.5-centos" \
  --set etcd.enabled=false \
  --set etcd.host={http://172.21.9.36:22379} \
  --set etcd.user="root" \
  --set etcd.password="123" \
  --set etcd.prefix="/apisix" \
  --set allow.ipList=""

```
apisix-ingress-controller install
```
helm install sitech-gray-ingress-controller ./apisix-ingress-controller \
  --set config.apisix.baseURL=http://sitech-gray-admin:9180/apisix/admin \
  --set config.apisix.adminKey=edd1c9f034335f136f87ad84b625c8f1 \
  --set image.repository="172.21.9.35:30002/gray-stare/gray-ingress" \
  --set image.tag="0.5.0" \
  --namespace gray-publish
```

**Comment by tokers** [comment] 2021-05-08 06:49
OK, the apisix base url `sitech-gray-admin` confuses me.

From the error log, your controller cannot communicate to apisix admin, could you try to send request to `sitech-gray-admin` from the controller container?

**Comment by pioneer-hash** [comment] 2021-05-08 06:57
> OK, the apisix base url `sitech-gray-admin` confuses me.
> 
> From the error log, your controller cannot communicate to apisix admin, could you try to send request to `sitech-gray-admin` from the controller container?

I I go inside pod of apisix-ingress-controller and get Route information directly it was successful
```
/ingress-apisix # wget http://apisix-admin:9180/apisix/admin/routes  --header="X-API-Key: edd1c9f034335f136f87ad84b625c8f1"
wget: bad address 'apisix-admin:9180'
/ingress-apisix # wget http://sitech-gray-admin:9180/apisix/admin/routes  --header="X-API-Key: edd1c9f034335f136f87ad84b625c8f1"
Connecting to sitech-gray-admin:9180 (10.111.0.24:9180)
saving to 'routes'
routes               100% |******************************************************************************************************|   908  0:00:00 ETA
'routes' saved
/ingress-apisix # ls
apisix-ingress-controller  conf                       routes
```

**Comment by tao12345666333** [comment] 2022-03-23 04:45
You can try deploying with the new version and see if the problem persists.

I'll close this issue because it's been too long. If your issue is not resolved, feel free to reopen it, or create a new issue. 

Thanks for your report.

**Closed by tao12345666333** 2022-03-23 04:45 UTC
