### ISSUE TITLE
suggest：proxy scheme should be in ApisixRoute not ApisixUpstream

### ISSUE THREAD

**Issue by myselfghost** [apache/apisix-ingress-controller#871] opened 2022-02-16 03:01 UTC
why:  In most scenarios, we only need to define a ApisixRoute, and we don't need to bother to define ApisixUpstream. but, if we proxy a grpc service , we have to define ApisixUpstream like 

```
apiVersion: apisix.apache.org/v1
kind: ApisixUpstream
metadata:
  name: yages
  namespace: ingress-apisix
spec:
  scheme: grpc
```
so suggest：proxy scheme should be in ApisixRoute not ApisixUpstream, that way we can do less work

**Comment by tao12345666333** [comment] 2022-02-16 06:05
We can take a discuss on mail list.

**Comment by tao12345666333** [comment] 2022-03-04 07:21
It's duplicate of  https://github.com/apache/apisix-ingress-controller/issues/864
I will close this one, using #864  for track.

**Closed by tao12345666333** 2022-03-04 07:21 UTC
Labels: triage/duplicate, discuss
