### ISSUE TITLE
request help: ApisixRoute doesn't effect

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-ingress-controller#958] opened 2022-04-08 07:51 UTC
### Issue description

When i apply below ingress.yml, it can create route for httpbin
```
# httpbin-ingress.yaml
# Note use apiVersion is networking.k8s.io/v1, so please make sure your
# Kubernetes cluster version is v1.19.0 or higher.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserver-ingress
spec:
  # apisix-ingress-controller is only interested in Ingress
  # resources with the matched ingressClass name, in our case,
  # it's apisix.
  ingressClassName: apisix
  rules:
    - host: local.httpbin.org
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  number: 80
            path: /
            pathType: Prefix
```
but when i apply below yml, it can't create the route of httpbin
```
# httpbin-route.yaml
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
    - name: rule1
      match:
        hosts:
          - local.httpbin.org
        paths:
          - /*
      backends:
        - serviceName: httpbin
          servicePort: 80
```

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): master
- your Kubernetes cluster version (output of kubectl version): minikube v1.18.1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): Big Sur

**Comment by Marco-Zheng** [comment] 2022-04-08 07:55
There always print the log 
```
E0408 15:54:29.765098   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixUpstream: failed to list *v2beta3.ApisixUpstream: the server could not find the requested resource (get apisixupstreams.apisix.apache.org)
E0408 15:54:29.960410   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixClusterConfig: failed to list *v2beta3.ApisixClusterConfig: the server could not find the requested resource (get apisixclusterconfigs.apisix.apache.org)
E0408 15:54:30.179900   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixRoute: failed to list *v2beta3.ApisixRoute: the server could not find the requested resource (get apisixroutes.apisix.apache.org)
E0408 15:54:30.616848   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixConsumer: failed to list *v2beta3.ApisixConsumer: the server could not find the requested resource (get apisixconsumers.apisix.apache.org)
2022-04-08T15:54:31+08:00       info    ingress/controller.go:606       service kube-system/k8s.io-minikube-hostpath not found
E0408 15:54:31.774710   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixTls: failed to list *v2beta3.ApisixTls: the server could not find the requested resource (get apisixtlses.apisix.apache.org)
E0408 15:54:31.878878   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixUpstream: failed to list *v2beta3.ApisixUpstream: the server could not find the requested resource (get apisixupstreams.apisix.apache.org)
E0408 15:54:32.233737   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixRoute: failed to list *v2beta3.ApisixRoute: the server could not find the requested resource (get apisixroutes.apisix.apache.org)
E0408 15:54:32.312883   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixClusterConfig: failed to list *v2beta3.ApisixClusterConfig: the server could not find the requested resource (get apisixclusterconfigs.apisix.apache.org)
E0408 15:54:32.687527   79831 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixConsumer: failed to list *v2beta3.ApisixConsumer: the server could not find the requested resource (get apisixconsumers.apisix.apache.org)
```

**Comment by Marco-Zheng** [comment] 2022-04-08 08:56
I just debug the ingress-controller and found that https://github.com/apache/apisix-ingress-controller/blob/f58f3d51889fe72609ca0b837b373e62306f9a3a/pkg/ingress/apisix_route.go#L65 worker for apisix route doesn't run

**Comment by tao12345666333** [comment] 2022-04-08 09:10
Can you give the difference directly?

**Comment by Marco-Zheng** [comment] 2022-04-08 09:15
> Can you give the difference directly?

Sorry, i updated the route of httpbin
```
# httpbin-route.yaml
apiVersion: apisix.apache.org/v2beta2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
    - name: rule1
      match:
        hosts:
          - local.httpbin.org
        paths:
          - /*
      backends:
        - serviceName: httpbin
          servicePort: 80
```

**Comment by Marco-Zheng** [comment] 2022-04-11 02:17
> The log you posted doesn't contain the actual error message.
> 
> Also, did you create the service first and then create the Ingress and ApisixRoute?

Yes, i create httpbin and expose the port 80, then create Ingress, it works, then i delete the Ingress and apply ApisixRoute, it not works, if the ApisixRoute depends on Ingress ?

**Comment by tokers** [comment] 2022-04-11 09:03
> > The log you posted doesn't contain the actual error message.
> > Also, did you create the service first and then create the Ingress and ApisixRoute?
> 
> Yes, i create httpbin and expose the port 80, then create Ingress, it works, then i delete the Ingress and apply ApisixRoute, it not works, if the ApisixRoute depends on Ingress ?

Nope, how did you configure the namespace discovery?

**Comment by tokers** [comment] 2022-04-11 09:04
> > > The log you posted doesn't contain the actual error message.
> > > Also, did you create the service first and then create the Ingress and ApisixRoute?
> > 
> > 
> > Yes, i create httpbin and expose the port 80, then create Ingress, it works, then i delete the Ingress and apply ApisixRoute, it not works, if the ApisixRoute depends on Ingress ?
> 
> Nope, how did you configure the namespace discovery?

I mean, only namespaces matched the namespace label selector (configured in APISIX Ingress Controller) will be watched.

**Comment by Marco-Zheng** [comment] 2022-04-11 09:28
> > > > The log you posted doesn't contain the actual error message.
> > > > Also, did you create the service first and then create the Ingress and ApisixRoute?
> > > 
> > > 
> > > Yes, i create httpbin and expose the port 80, then create Ingress, it works, then i delete the Ingress and apply ApisixRoute, it not works, if the ApisixRoute depends on Ingress ?
> > 
> > 
> > Nope, how did you configure the namespace discovery?
> 
> I mean, only namespaces matched the namespace label selector (configured in APISIX Ingress Controller) will be watched.

I deployed httpbin service under default namespace by below command
```
kubectl run httpbin --image kennethreitz/httpbin --port 80
kubectl expose pod httpbin --port 80
```

**Comment by tao12345666333** [comment] 2022-04-15 11:47
I couldn't reproduce it, you can try to reinstall or check your environment.  
For this project we have e2e tests for coverage

**Comment by tao12345666333** [comment] 2022-07-18 04:02
It has not been updated for too long and I will close it. If your issue is not resolved, please open it easily and provide more detailed information

**Closed by tao12345666333** 2022-07-18 04:02 UTC
Labels: triage/needs-information, triage/not-reproducible
