### ISSUE TITLE
request help: failed to list upstreams in APISIX: unexpected non-empty object

### ISSUE THREAD

**Issue by riskgod** [apache/apisix-ingress-controller#663] opened 2021-09-03 08:04 UTC
hey in k8s（helm chart install version 2.7） 
my apisix-ingress-controller always through this err.  What is this mean?
```
failed to list upstreams in APISIX: unexpected non-empty object
```

**Comment by tokers** [comment] 2021-09-03 09:20
So what's the version of your apisix-ingress-controller?

**Comment by riskgod** [comment] 2021-09-03 09:53
> So what's the version of your apisix-ingress-controller?

```
apache/apisix-ingress-controller:1.0.0
```

**Comment by riskgod** [comment] 2021-09-03 09:57
The err also shows
```
 failed to convert upstream item
```

**Comment by tao12345666333** [comment] 2021-09-05 01:48
@gxthrj PTAL

**Comment by tokers** [comment] 2021-09-05 09:30
This result was caused by the marshal process of apisix upstream.

@riskgod Could you try to send requests to apisix admin service and see the result? The request likes:

```shell
curl http://apisix-admin:9180/apisix/admin/upstreams
```

`X-API-Key` should be carried so that the authentication can be passed.

**Comment by gxthrj** [comment] 2021-09-13 06:43
@riskgod any update? please show the configuration of ingress controller.

**Comment by Donghui0** [comment] 2021-09-13 12:09
@riskgod It should be the format of Upstream.nodes is wrong.
Wrong format:
{"1.1.1.1:8080": 1, "2.2.2.2:8080": 1}
Correct format:
[{"host": "1.1.1.1", "port": 8080, "weight": 100, "priority": 0}]

Use the following command to query:
curl http://apisix-admin:9180/apisix/admin/upstreams -H "X-API-KEY: secretKey"  | python -m json.tool

**Comment by tokers** [comment] 2021-09-13 13:20
> If the Apache APISIX cluster is managed **only** by the APISIX Ingress controller, there won't have any object-like nodes, are there some legacy data in the cluster before the ingress controller takes over it.

By the way, we can consider to support object like nodes.

**Comment by gxthrj** [comment] 2021-09-15 03:04
@riskgod Is there any update? Has this problem been resolved in your environment?

**Comment by gxthrj** [comment] 2021-09-26 01:58
The stale issue, feel free to reopen.

**Closed by gxthrj** 2021-09-26 01:58 UTC
