### ISSUE TITLE
always print err log: reqFailed to watch *v2beta3. in k8s v1.19.3, but not in k8s v1.17

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix-ingress-controller#874] opened 2022-02-17 02:53 UTC
### Issue description

my  apisix ingress controller always print err logs like this(in the  k8s v1.19.3, but in the k8s v1.17,it do not print the logs)
Is that any problem ? 
E0217 10:45:31.493142       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixConsumer: failed to list *v2beta3.ApisixConsumer: the server could not find the requested resource (get apisixconsumers.apisix.apache.org)
[GIN] 2022/02/17 - 10:45:34 | 200 |      127.99µs |    172.16.11.15 | GET      "/healthz"
[GIN] 2022/02/17 - 10:45:34 | 200 |      47.545µs |    172.16.11.15 | GET      "/healthz"
E0217 10:45:38.088233       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixUpstream: failed to list *v2beta3.ApisixUpstream: the server could not find the requested resource (get apisixupstreams.apisix.apache.org)
E0217 10:45:43.308362       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v2beta3.ApisixTls: failed to list *v2beta3.ApisixTls: the server could not find the requested resource (get apisixtlses.apisix.apache.org)

I deploy the apisix ingress like this ：
helm install apisix-ingress-controller apisix/apisix-ingress-controller --version=0.9.0  --namespace ingress-apisix    \
 --set config.apisix.serviceName=apisix-gw-lb  --set config.apisix.serviceNamespace=default --set config.apisix.servicePort=9080 --set config.logLevel=warn  --set config.apisix.adminKey=edd1c9f034335f136f87ad84b625c8f1

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.14
- your Kubernetes cluster version (output of kubectl version): 1.19.3
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):
  run by helm  as description above.

**Comment by tao12345666333** [comment] 2022-02-17 02:55
Thanks for your report, it is a duplicate of #873 
I will close this issue, we can use #873 to track.

**Closed by tao12345666333** 2022-02-17 02:55 UTC
Labels: triage/duplicate
